<?php

namespace AdminDashboard\Database\Seeders;

use Illuminate\Database\Seeder;
use AdminDashboard\Models\Administrator;
use AdminDashboard\Models\Counselor;
use AdminDashboard\Models\Client;

class AdminDashboardSeeder extends Seeder
{
    public function run(): void
    {
        Administrator::insert([
            ['name' => 'Nur Aina Zulkifli', 'email' => 'aina@werta.com', 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Marcus Tan', 'email' => 'marcus@werta.com', 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
        ]);

        Counselor::insert([
            [
                'name' => 'Nurul Huda',
                'qualification' => 'M.Couns',
                'email' => 'nurul@werta.com',
                'status' => 'pending',
                'display_title' => 'Counselor',
                'specialties' => json_encode(['Academic Anxiety']),
                'languages' => json_encode(['English', 'Bahasa Melayu']),
                'session_modes' => json_encode(['Online']),
                'state' => 'Selangor',
                'years_experience' => 3,
                'bio' => 'Nurul offers warm and attentive conversations for students experiencing study-related stress. Her sessions prioritize a comfortable atmosphere for gentle self-exploration.',
                'rate_individual' => 85.00,
                'is_sample' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. James Lee',
                'qualification' => 'PhD Clin Psych',
                'email' => 'james@werta.com',
                'status' => 'pending',
                'display_title' => 'Counselor',
                'specialties' => json_encode(['Depression & Mood']),
                'languages' => json_encode(['English', 'Mandarin']),
                'session_modes' => json_encode(['Online', 'In person']),
                'state' => 'Kuala Lumpur',
                'years_experience' => 12,
                'bio' => 'Dr. James works with adults dealing with prolonged emotional strain and mood fluctuations. He focuses on thoughtful inquiry and collaborative discussions to support personal insight.',
                'rate_individual' => 190.00,
                'is_sample' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Siti Rahman',
                'qualification' => 'M.Couns',
                'email' => 'siti@werta.com',
                'status' => 'approved',
                'display_title' => 'Counselor',
                'specialties' => json_encode(['Academic Anxiety', 'Depression & Mood']),
                'languages' => json_encode(['English', 'Bahasa Melayu']),
                'session_modes' => json_encode(['Online', 'In person']),
                'state' => 'Kuala Lumpur',
                'years_experience' => 7,
                'bio' => 'Siti focuses on providing a compassionate, non-judgmental space for clients to explore their daily challenges. Her approach incorporates reflective conversations tailored to each individual\'s pace.',
                'rate_individual' => 120.00,
                'is_sample' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kevin Ong',
                'qualification' => 'B.Psych (Hons)',
                'email' => 'kevin@werta.com',
                'status' => 'rejected',
                'display_title' => 'Counselor',
                'specialties' => json_encode(['Career Transitions']),
                'languages' => json_encode(['English', 'Mandarin']),
                'session_modes' => json_encode(['In person']),
                'state' => 'Melaka',
                'years_experience' => 2,
                'bio' => 'Kevin provides structured conversations around early career questions and workplace adjustments. He assists clients in clarifying personal goals and communication styles.',
                'rate_individual' => 80.00,
                'is_sample' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grace Ling',
                'qualification' => 'M.Couns',
                'email' => 'grace.ling@werta.com',
                'status' => 'approved',
                'display_title' => 'Counselor',
                'specialties' => json_encode(['Relationship Counseling', 'Career Transitions']),
                'languages' => json_encode(['English', 'Mandarin']),
                'session_modes' => json_encode(['Online']),
                'state' => 'Sarawak',
                'years_experience' => 9,
                'bio' => 'Grace provides supportive guidance to help individuals navigate interpersonal relationships and major life changes. She emphasizes collaborative goal-setting and active listening in every session.',
                'rate_individual' => 150.00,
                'is_sample' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Joshua Justin',
                'qualification' => 'M.A. Counseling',
                'email' => 'joshua.justin@werta.com',
                'status' => 'approved',
                'display_title' => 'Counselor',
                'specialties' => json_encode(['Academic Anxiety', 'Career Transitions']),
                'languages' => json_encode(['English', 'Bahasa Melayu']),
                'session_modes' => json_encode(['Online', 'In person']),
                'state' => 'Sabah',
                'years_experience' => 5,
                'bio' => 'Joshua works with students and young professionals seeking clarity in their educational and career journeys. He values practical discussions and supportive exploration in a calm setting.',
                'rate_individual' => 90.00,
                'is_sample' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ananthi Subramaniam',
                'qualification' => 'M.Couns',
                'email' => 'ananthi@werta.com',
                'status' => 'approved',
                'display_title' => 'Counselor',
                'specialties' => json_encode(['Depression & Mood', 'Relationship Counseling']),
                'languages' => json_encode(['English', 'Bahasa Melayu']),
                'session_modes' => json_encode(['In person', 'Online']),
                'state' => 'Selangor',
                'years_experience' => 11,
                'bio' => 'Ananthi facilitates open dialogues to assist clients in understanding emotional patterns and family dynamics. Her practice centers on empathy, steady encouragement, and clear personal reflection.',
                'rate_individual' => 160.00,
                'is_sample' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chen Wei Xiang',
                'qualification' => 'B.Psych (Hons), M.Couns',
                'email' => 'weixiang@werta.com',
                'status' => 'approved',
                'display_title' => 'Counselor',
                'specialties' => json_encode(['Academic Anxiety', 'Relationship Counseling']),
                'languages' => json_encode(['English', 'Mandarin', 'Bahasa Melayu']),
                'session_modes' => json_encode(['Online']),
                'state' => 'Pulau Pinang',
                'years_experience' => 4,
                'bio' => 'Wei Xiang offers thoughtful guidance for individuals managing academic pressures and communication issues. He encourages clients to develop self-awareness through structured conversations.',
                'rate_individual' => 100.00,
                'is_sample' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Faridah binti Osman',
                'qualification' => 'M.Ed. Guidance & Counseling',
                'email' => 'faridah@werta.com',
                'status' => 'approved',
                'display_title' => 'Counselor',
                'specialties' => json_encode(['Depression & Mood', 'Career Transitions']),
                'languages' => json_encode(['English', 'Bahasa Melayu']),
                'session_modes' => json_encode(['In person']),
                'state' => 'Johor',
                'years_experience' => 14,
                'bio' => 'Faridah supports adults coping with low mood and transitional stress through conversational counseling. She works with clients to build steady daily routines and constructive coping habits.',
                'rate_individual' => 180.00,
                'is_sample' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Client::insert([
            ['name' => 'Ahmad bin Ali', 'email' => 'ahmad@example.com', 'path' => 'A', 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Grace Wong', 'email' => 'grace@example.com', 'path' => 'B', 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rajesh Kumar', 'email' => 'rajesh@example.com', 'path' => 'A', 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}